export const MAKE_PAYMENT_ORDER_REQUEST = 'MAKE_PAYMENT_ORDER_REQUEST'
export const MAKE_PAYMENT_ORDER_SUCCESS = 'MAKE_PAYMENT_ORDER_SUCCESS'
export const MAKE_PAYMENT_ORDER_FAIL = 'MAKE_PAYMENT_ORDER_FAIL'

export const VERIFY_PAYMENT_ORDER_REQUEST = 'VERIFY_PAYMENT_ORDER_REQUEST'
export const VERIFY_PAYMENT_ORDER_SUCCESS = 'VERIFY_PAYMENT_ORDER_SUCCESS'
export const VERIFY_PAYMENT_ORDER_FAIL = 'VERIFY_PAYMENT_ORDER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'