export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'

export const VERIFY_PAY_ORDER_REQUEST = 'VERIFY_PAY_ORDER_REQUEST'
export const VERIFY_PAY_ORDER_SUCCESS = 'VERIFY_PAY_ORDER_SUCCESS'
export const VERIFY_PAY_ORDER_FAIL = 'VERIFY_PAY_ORDER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'